In [2]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [3]:
squared=[]
for i in list_a:
  squared.append(i*i)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [5]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [6]:
import numpy as np


In [7]:
arr1 = np.array(list_a)

In [8]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [10]:
arr2 =np.array([2,4,6,8])
arr2*2

array([ 4,  8, 12, 16])

In [11]:
#Methods to create an array

#using python list

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#using numpy arange
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3 = np.random.randn(1,10)
arr4 = np.random.rand(1,10)
print(arr3)
print(arr4)

[[ 8.75962590e-01 -1.01513931e+00  1.59171151e+00 -7.54754267e-01
  -1.08631893e+00 -1.56375630e-03 -7.24266357e-01  3.95218905e-01
   5.19427881e-02 -1.52024138e+00]]
[[0.00869468 0.65386117 0.06954358 0.18341606 0.49688242 0.23965073
  0.47007232 0.47593686 0.37572831 0.57106784]]


In [14]:
arr1.dtype

dtype('int64')

In [15]:
arr1.shape

(10,)

In [16]:
arr3.dtype

dtype('float64')

In [17]:
arr1.size

10

In [18]:
arr1.ndim

1

In [20]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d.size

9

In [22]:
arr2d.shape

(3, 3)

In [23]:
arr2d.ndim

2

In [26]:
arr2d1 = np.random.rand(5,4) #create an array of 5 rows x 4 columns with rand numbers
arr2d1

array([[0.0641718 , 0.22601294, 0.18458307, 0.97651111],
       [0.64080289, 0.32749086, 0.74310925, 0.53416561],
       [0.63150054, 0.78854259, 0.89186557, 0.8380129 ],
       [0.35173763, 0.90067627, 0.59189363, 0.87034466],
       [0.67294966, 0.40532805, 0.15843348, 0.9158584 ]])

In [27]:
arr3d = np.random.rand(3,4,5) #create an array of 3 copies x 4 rows x 5 column
arr3d

array([[[0.54233147, 0.11234923, 0.58197236, 0.61088495, 0.33928152],
        [0.6530127 , 0.10846984, 0.20658287, 0.32390061, 0.58531756],
        [0.9202696 , 0.36081572, 0.64468756, 0.21958588, 0.30751292],
        [0.461204  , 0.88206702, 0.82565293, 0.25880187, 0.97307875]],

       [[0.73581616, 0.73534318, 0.55849604, 0.33194234, 0.23236794],
        [0.15640756, 0.91847081, 0.33769076, 0.80599315, 0.23028532],
        [0.22055836, 0.57912187, 0.68050877, 0.5160991 , 0.42532303],
        [0.50858862, 0.95093641, 0.32509783, 0.12028184, 0.22885525]],

       [[0.35544962, 0.20430397, 0.98170528, 0.92221722, 0.50537697],
        [0.8103408 , 0.19354054, 0.41934088, 0.46833832, 0.08076953],
        [0.38052103, 0.49846798, 0.31094554, 0.23635418, 0.36484709],
        [0.83261575, 0.68007052, 0.86255668, 0.63123882, 0.32550234]]])

In [38]:
arr3d1 = np.arange(64)
arr3d1.reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [40]:
zeros = np.zeros(6)
zeros

array([0., 0., 0., 0., 0., 0.])

In [41]:
zeros.dtype

dtype('float64')

In [44]:
z2 = np.zeros((6,5))
z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
o1 = np.ones((5,7))
o1

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
identity = np.eye(5,5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.ones((4,4))*15

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [52]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])