In [1]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [2]:
squared=[]
for i in list_a:
  squared.append(i*i)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [3]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [4]:
import numpy as np


In [5]:
arr1 = np.array(list_a)

In [6]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [8]:
arr2 =np.array([2,4,6,8])
arr2*2

array([ 4,  8, 12, 16])

In [9]:
#Methods to create an array

#using python list

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#using numpy arange
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr3 = np.random.randn(1,10)
arr4 = np.random.rand(1,10)
print(arr3)
print(arr4)

[[ 0.73305455 -2.07582751 -0.05766806  0.75470271  0.51498201 -0.44685158
  -1.2276941  -1.23627405  0.13200615 -0.52757192]]
[[0.10645705 0.50064877 0.53914623 0.69749167 0.86717456 0.06393367
  0.36801868 0.19748725 0.7649882  0.37673425]]


In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr1.shape

(10,)

In [14]:
arr3.dtype

dtype('float64')

In [15]:
arr1.size

10

In [16]:
arr1.ndim

1

In [17]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d.size

9

In [19]:
arr2d.shape

(3, 3)

In [20]:
arr2d.ndim

2

In [21]:
arr2d1 = np.random.rand(5,4) #create an array of 5 rows x 4 columns with rand numbers
arr2d1

array([[0.39400287, 0.38631665, 0.51677388, 0.27605734],
       [0.85804943, 0.9139459 , 0.62115014, 0.43167072],
       [0.04723674, 0.68173936, 0.65569351, 0.47276878],
       [0.95341807, 0.46401365, 0.00964089, 0.63985229],
       [0.08361702, 0.16858497, 0.05173778, 0.40098191]])

In [22]:
arr3d = np.random.rand(3,4,5) #create an array of 3 copies x 4 rows x 5 column
arr3d

array([[[0.39716295, 0.12671417, 0.40642884, 0.42228319, 0.79503089],
        [0.50521387, 0.194506  , 0.3238516 , 0.39690317, 0.65435927],
        [0.34285537, 0.24105699, 0.13531836, 0.22368432, 0.8137056 ],
        [0.14394668, 0.79658172, 0.46985396, 0.01058208, 0.55997074]],

       [[0.90900932, 0.0920554 , 0.23610253, 0.11202234, 0.621468  ],
        [0.61847166, 0.10881056, 0.33772951, 0.06281211, 0.18018754],
        [0.67230747, 0.01935406, 0.19598575, 0.44085063, 0.02175619],
        [0.59217907, 0.90413782, 0.22836982, 0.47042778, 0.0561694 ]],

       [[0.88842534, 0.41517717, 0.01338425, 0.2498194 , 0.71557834],
        [0.17243109, 0.31923462, 0.70255631, 0.33471153, 0.28437   ],
        [0.96068465, 0.96360598, 0.23054625, 0.01565865, 0.70715489],
        [0.59421906, 0.02567911, 0.87405492, 0.02929397, 0.78081881]]])

In [23]:
arr3d1 = np.arange(64)
arr3d1.reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [24]:
zeros = np.zeros(6)
zeros

array([0., 0., 0., 0., 0., 0.])

In [25]:
zeros.dtype

dtype('float64')

In [26]:
z2 = np.zeros((6,5))
z2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
o1 = np.ones((5,7))
o1

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [28]:
identity = np.eye(5,5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.ones((4,4))*15

array([[15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.],
       [15., 15., 15., 15.]])

In [30]:
np.full((4,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [31]:
arr2d1 = np.arange(20).reshape(4,5)
arr2d2 = np.arange(20,40).reshape(4,5)
print(arr2d1)
print(arr2d2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [32]:
#Arrays with same shape and dimensions can be computed arithmetically

arr2d1 + arr2d2

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [33]:
arr2d1 * arr2d2

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [34]:
arr2d1-100

array([[-100,  -99,  -98,  -97,  -96],
       [ -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86],
       [ -85,  -84,  -83,  -82,  -81]])

In [36]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,0])


In [37]:
arr1[3]

np.int64(4)

In [38]:
arr1[-4]

np.int64(7)

In [39]:
arr1[3:6]

array([4, 5, 6])

In [40]:
arr2d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
arr2d1[2,2:5]

array([12, 13, 14])

In [43]:
arr2d1[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [45]:
#[[2,3],
# [7,8]]

arr2d1[:2,2:4]


array([[2, 3],
       [7, 8]])

In [46]:
arr2d1[3,:]

array([15, 16, 17, 18, 19])

In [49]:
arr2d1[:,3]

array([ 3,  8, 13, 18])

In [52]:
arr2d1[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [53]:
arr2d1[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [54]:
arr2d1[::-2]

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

In [56]:
a = np.array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[100]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])
a.ndim

31

In [59]:
arr = np.array(range(20))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
arr[arr%5==0]

array([ 0,  5, 10, 15])

In [64]:
#Odd numbers only
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [65]:
#Numbers >5 and <15
arr[(arr>5) & (arr<15)] #and: &, or: |

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])